export const GQL_SCHEMAS = Object.freeze({
    CheckExaminerForAdjusterLicenseState: 'checkExaminerForAdjusterLicenseState',
    AdjusterLicenseStates: 'adjusterLicenseStates',
    APP_LOGS: 'app-log',
    CLAIM_MASTER: 'claim-master',
    DB2CLAIMS: 'db2claims',
    CLAIM_NARRATIVE: 'claim-narrative',
    LITIGATION: 'litigation',
    RESOURCE: 'resource',
    CONTACT: 'contact',
    ASSOC_CLAIM: 'associated-claims',
    INSURED_CONTACT: 'insured-contact',
    ACCOUNTING: 'accounting',
    CORRESPONDENCE: 'correspondence',
    USER: 'user',
    REFERENCE: 'reference',
    CONFIG: 'config',
    CLAIMS_COMMON: 'claims-common',
    CLAIM_EXAMINER: 'claim-examiner',
    CLAIM_BRANCH: 'claim-branch',
    POLICY: 'policy',
    POLICY_CODINGS: 'claim-policy-grid',
    LEGAL_CLAIM: 'legal-claim',
    LEGAL_COMPANIES: 'legal-companies',
    UL_Claims: 'ul-claims',
    ASSOCIATED_POLICY_CONTRACT: 'associated-policy-contract',
    TEMPLATE_TEXT: 'template-text',
    CourtSuits: 'court-suits',
    SUPPORT_TYPE: 'support-type',
    Pre_Trail_Memo: "Pre-Trail-Memo",
    TASK_TYPE: 'task-type',
    NOTIFICATION_MESSAGE_TYPE: 'notification-message-type',
    ClaimDetailFlagTypes: 'claim-detail-flag-types',
    Notification_Types: "notification-comment",
    Claim_SUPPORT_TYPES: "notifications",
    Notification_Roles: "notificationRoles",
    COMPANY_NAMES: 'g2companyname',
    CLAIM_RISK_CODING: 'claim-risk-coding',
    CLAIM_CLAIMANT: 'claim-claimant',
    PROPERTY_POLICY: 'property-policy',
    OpenLineBobCoverage: 'open-line-bob-coverage',
    POLICYRESCISSION: 'policy-rescission',
    WC_CLAIM_CLAIMANT: 'wc-claim-claimant',
    WC_REIMBURSEMENT: 'wc-reimbursement',
    WC_REIMBURSEMENT_COMPANY_DOLLAR: 'wc-reimbursement-company-dollar',
    WC_REIMBURSEMENT_PRIOR_TPA_PAID: 'wc-reimbursement-prior-tpa-paid',
    WC_REIMBURSEMENT_ADJUSTMENTS: 'wc-reimbursement-adjustments',
});

export const GQL_MUTATION = Object.freeze({
    IS_MUTATION: true,
    IS_NOT_MUTATION: false,
});