
export const COMPANY_NAME = Object.freeze({
    GSI_GENERAL_STAR_INDEMNITY_CO: 1,
    GSN_GENERAL_STAR_NATIONAL_INSURANCE_CO: 2,
    GIC_GENESIS_INSURANCE_COMPANY: 3,
    GRC_GENERAL_REINSURANCE_CORPORATION: 4,
    OTHER: 5
});